version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: prod_password
      POSTGRES_DB: ticketing_prod
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - postgres_prod_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: always

  ticket-service:
    build: ./ticket-service
    environment:
      DB_USER: prod_user
      DB_PASSWORD: prod_password
      DB_NAME: ticketing_prod
      DB_HOST: postgres
    depends_on:
      - postgres
    restart: always

  support-service:
    build: ./support-service
    environment:
      DB_USER: prod_user
      DB_PASSWORD: prod_password
      DB_NAME: ticketing_prod
      DB_HOST: postgres
    depends_on:
      - postgres
    restart: always

  notification-service:
    build: ./notification-service
    restart: always

  reporting-service:
    build: ./reporting-service
    environment:
      DB_USER: prod_user
      DB_PASSWORD: prod_password
      DB_NAME: ticketing_prod
      DB_HOST: postgres
    depends_on:
      - postgres
    restart: always

  api-gateway:
    build: ./api-gateway
    ports:
      - "8083:80"
    depends_on:
      - ticket-service
      - support-service
      - reporting-service
    restart: always

volumes:
  postgres_prod_data:
