apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  DB_USER: "k8s_user"
  DB_PASSWORD: "k8s_password"
  DB_NAME: "ticketing"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_SECURE: "false"
  SMTP_USER: "amaamoun99@gmail.com"
  SMTP_PASS: "dnof wgfc rfwi nxdb"
  SMTP_FROM: "Support <amaamoun99@gmail.com>"
