apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      containers:
      - name: ticket-service
        image: ticket-service:latest
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          value: "postgres"
        - name: DB_USER
          value: "k8s_user"
        - name: DB_PASSWORD
          value: "k8s_password"
        - name: DB_NAME
          value: "ticketing"
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-service
spec:
  type: ClusterIP
  selector:
    app: ticket-service
  ports:
  - port: 3001
    targetPort: 3001
